# Generated by Django 4.0.3 on 2022-03-26 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shrink_App', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='image',
            field=models.ImageField(default=0, upload_to='media'),
        ),
    ]
